version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DATABASE
    ports:
      - 5432:5432
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/init.sql
